# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 22e1f009051d775d4bbb6ebbebcb0ed4070bb7aa2c05c4aa41b01679e9d64862b1b8acb865c8cbe76bd8511206ef497a2a87e45b14d87065f73b8c515fedd65a

test:
  secret_key_base: 117cdf366c57aaade28a233ca7a8440e620c8404cd67592ea93fe7a365d479f1b0fadcd6c0a0925aed007c4c7a64bb62ba8b7b675c4d9f970164336898090744

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
